### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Kevadroz** [Kevadroz/NoControllerGlyphs#3]
- [ ] Create exclusion system.
- [ ] Make glyphs appear and disappear when a controller button / keyboard key is pressed.
- [ ] Add mixed input support.
  - [ ] Add support for excluding keys from this system.

**Comment by ghost** [comment]
* [ ] fix it showing still
